GridLayout:
    cols: 1
    Label:
        id: moeda1
        text: ""
    Label:
        id: moeda2
        text: ""
    Label:
        id: moeda3
        text: ""
    Label:
        id: moeda4
        text: ""
    Label:
        id: moeda5
        text: ""
    Label:
        id: moeda6
        text: ""
    Label:
        id: moeda7
        text: ""
    Label:
        id: moeda8
        text: ""
    Label:
        id: moeda9
        text: ""
    Label:
        id: moeda10
        text: ""